/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define FUSE_HOTFIX_VERSION 4

#define FUSE_MAJOR_VERSION 3

#define FUSE_MINOR_VERSION 17

#define FUSE_RC_VERSION 

